<?php
/**
 * Login class
 * @author: Timur Misharin
 * @version: 0.1
 */
require_once "../config/Page.php";
require_once "../config/db.php";

class Login extends Page{

    public function __construct()
    {
        parent::__construct();
        //TODO: constructor
    }
    public function __destruct()
    {
        parent::__destruct();
        // TODO: Change the autogenerated stub
    }
}